<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-1">
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-hotline')->toHtml(); ?>
                    <div class="language-currency">
                            <?php echo $this->getChildHtml("store_language"); ?>
                            <?php echo $this->getChildHtml("currency"); ?>
                    </div>
                        
                </div>

                <div class="col-lg-6">
                    <div class="right-content">
                        <div class="customer-links" data-move="customer-mobile">
                            <h3><?php echo __('My Account');?></h3>
                            <?php echo $this->getChildHtml("toplinks-header"); ?>
                        </div>
						<div class="search-wrapper">
							<?php echo $this->getChildHtml("topSearch"); ?>
						</div>
                         <div class="minicart-header" data-move="minicart-mobile">
                            <?php echo $this->getChildHtml("minicart"); ?>
                        </div>
                      
                         
                     </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-bottom ontop-element">
        <div class="container">
            <div class="desktop-menu">
                
                <div class="horizontal-block">
                    <?php
                        if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                            echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                        } else {
                                echo $this->getChildHtml("horizontal-css");
                        }
                    ?>
                </div>
                <div class="logo-container">
                    <?php echo $this->getChildHtml("logo"); ?>
                </div>
                <div class="header-menu-right">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal-bonus')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
