<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-2-style">
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="language-currency">
                        <?php echo $this->getChildHtml("store_language"); ?>
                        <?php echo $this->getChildHtml("currency"); ?>
                    </div>
                </div>

                <div class="col-lg-9">
                    <div class="header-top-r">
						<div class="customer-links" data-move="customer-mobile">
							<h3><?php echo __('My Account');?></h3>
							<?php echo $this->getChildHtml("toplinks-header"); ?>
						</div>
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('location-link-header')->toHtml(); ?>
							
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-middle">
        <div class="container">
			<div class="content">
				<div class="l-content">
					<div class="logo-container">
						<?php echo $this->getChildHtml("logo"); ?> 
					</div>
				</div>

				<div class="search-container">
					<?php echo $this->getChildHtml("topSearch"); ?>
				</div>

				<div class="cms-header">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('hotline-shop')->toHtml(); ?>
				</div>

				<div class="minicart-header" data-move="minicart-mobile">
					<?php echo $this->getChildHtml("minicart"); ?>
				</div>	
			</div>
        </div>
    </div>

    <div class="header-bottom ontop-element">
        <div class="container">
            <div class="desktop-menu">
                <div class="vertical-block">
                    <?php
                    if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-vertical')->toHtml();
                    } else {
                        echo $this->getChildHtml("vertical-css");
                    }
                    ?>
                </div>

                <div class="horizontal-block">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml(); ?>
                  
                </div>
            </div>
        </div>
    </div>
</div>
